# Generated by Django 5.0.1 on 2025-10-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('for_new_user', models.BooleanField(default=False)),
                ('for_member', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'Coupon',
                'ordering': ['-created_at'],
            },
        ),
    ]
